#!/bin/sh


if [ $# -ne  2 ]
then
    echo -e "
    clone yourname.yoursurname project_name\n
    e.g: clone jordan.vitou PSU_malloc_2019\n"
fi

#function sleepy()
#{
#    sleep 1
#    echo -e "\033[1;5;31m It's (name.surname + project name)\e\n\n\033[0m"
#    echo -e "\033[1;5;31mClone in current repository!!! [Y||N]\n\n\033[0m"
#    read output
#    if [ $output = 'Y' ]; then
#        cd .
#        echo -e "\033[1;5;31mClone here\n\n\033[0m"
#        echo -e "\033[1;5;31m(name.surname + project name)\e\n\n\033[0m"
#    elif [ $output = 'N' ]; then
#        echo -e "Go to \033[1;5;31mWorking directory\n\n\033[0m"
#        cd
#        cd WORK/TEK2/
#    else
#        exit 0
#    fi
#}


#sleepy
if [ $# -eq 2 ]
   then
       git clone git@git.epitech.eu:/$1@epitech.eu/$2
fi
